import {
    DECISION_COLOR_SET,
    DECISION_COLOR_SRGB_LIGHTNESS_SCALE,
    DECISION_COLOR_SRGB_LIGHTNESS_VALUE,
    DECISION_COLOR_VALUE,
} from '../../../../constants';

export const VALUE_NAME = 'SRGBLightnessValue';
export const FALLBACK_VALUE = 0;
export const REF_CHECKED_TYPES = [
    DECISION_COLOR_SRGB_LIGHTNESS_VALUE,
    DECISION_COLOR_SRGB_LIGHTNESS_SCALE,
    DECISION_COLOR_VALUE,
    DECISION_COLOR_SET,
];
